version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: qwen-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: qwen_db
      MYSQL_USER: qwen_user
      MYSQL_PASSWORD: qwen_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - qwen_network

  qwen-app:
    build: .
    container_name: qwen-app
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: qwen_user
      MYSQL_PASSWORD: qwen_password
      MYSQL_DB: qwen_db
    depends_on:
      - mysql
    networks:
      - qwen_network

volumes:
  mysql_data:

networks:
  qwen_network:
    driver: bridge